# 1) 
# print("Hola UTN")
# 2) 
# print(3+5)
# 3)
# print(10-5)
# 4)
# print(10-15)
# 5)
# print(4*10)
# 6)
# print(10/2)
# 7)
#print(10/0)
#Cuando se divide por 0 arroja un error, debido a que la divison por 0 es imposible, el error es el siguiente: 
#ZeroDivisionError: division by zero
# 8)
# print((10+3)*(6+6))
# 9)
# print(10%2)
# 10)
# print(10%3)
# 11)
# variableA = 10
# variableB = 5
# print(variableA+variableB)
# print(variableA-variableB)
# print(variableA*variableB)
# print(variableA/variableB)