# 1)
# nombre = input("Cual es tu nombre?: ")
# print("Hola "+nombre+"!")
# 2)
# numero1 = int(input("Ingresa un numero: "))
# numero2 = int(input("Ingresa otro numero: "))
# print("La suma de estos numeros es:", numero1+numero2)
#3)
# nombre = input("Cual es tu nombre?: ")
# apellido = input("Cual es tu apellido? ")
# edad = input("Cuantos años tenes?: ")
# print("Hola", nombre, apellido, "tu edad es", edad, "años")
#4)
#nombre = input("Cual es tu nombre?: ")
# comision = int(input("Nro Comision: "))
# asignatura = input("Asignatura: ")
# docente = input("Docente: ")
# presente = input("Estuviste presente?: ")
# print("El alumno", nombre, "de la comision", comision, "en la asignatura", asignatura, "con docencia de", docente, "afirma que", presente, "estuvo presente")
#5)
# lado = int(input("Inserta la longitud de un lado del cuadrado: "))
# cuadrado = lado*4
# print("La superficie del cuadrado es de", cuadrado,"metros.")
#6)
# lado1 = int(input("Inserta la longitud de un lado del rectangulo: "))
# lado2 = int(input("Inserta la longitud del otro lado del rectangulo: "))
# rectangulo = (lado1*2)+(lado2*2)
# print("La superficie del rectangulo es de", rectangulo,"metros.")
#7)
# base = int(input("Inserte la longitud de la base del triangulo: "))
# altura = int(input("Inserte la longitud de la altura del triangulo: "))
# triangulo = base*altura/2
# print("La superficie del triangulo es de", triangulo,"metros.")
#8)
# nombre = input("Inserte el nombre del producto: ") 
# precio = int(input("Inserte el nombre del producto: ")) 
# iva = 1.21
# precioIva = precio*iva
# print("El precio con IVA de", nombre, "es de $"+str(precioIva))
#9)
# print("Calculadora de promedios")
# alumno = input("Cual es tu nombre?: ")
# nota1 = int(input("Nota 1: "))
# nota2 = int(input("Nota 2: "))
# nota3 = int(input("Nota 3: "))
# promedio = (nota1+nota2+nota3)/3
# print(alumno,"tu promedio es de: ", promedio)
#10)
# nombre = input("Cual es tu nombre?: ")
# edad = int(input("Cuantos años tenes?: "))
# futuro = edad+10
# print(nombre,"en 10 años vas a tener", futuro, "años")